### PR TITLE
Build with clang 3.7

### PR DESCRIPTION
**Pull request by baruch**
clang 3.2 is rather old by now, this work brings us up to clang 3.7.

### CODE REVIEW

**Comment by vmalloc** [comment]
Thanks!

**Comment by baruch** [comment]
You can also close the other three open bugs.

BTW, the interactive reader fails to work due to a missing traces.so library for it, is it still in use? What files need to be part of that shared library?

**Comment by vmalloc** [comment]
@baruch I'll have to check. Can you open a separate issue for it?

**Comment by baruch** [comment]
I've opened issue #6 for this.

**Pull request merged**
